
char str[MAX][20] = {
    "abstract",     // 3
    "assert",       // 4
    "boolean",      // 5
    "break",        // 6
    "byte",         // 7
    "case",         // 8
    "catch",        // 9
    "char",         // 10
    "class",        // 11
    "continue",     // 12
    "default",      // 13
    "do",           // 14
    "double",       // 15
    "else",         // 16
    "enum",         // 17
    "extends",      // 18
    "final",        // 19
    "finally",      // 20
    "float",        // 21
    "for",          // 22
    "if",           // 23
    "implements",   // 24
    "import",       // 25
    "int",          // 26
    "interface",    // 27
    "instanceof",   // 28
    "long",         // 29
    "native",       // 30
    "new",          // 31
    "package",      // 32
    "private",      // 33
    "protected",    // 34
    "public",       // 35
    "return",       // 36
    "short",        // 37
    "static",       // 38
    "strictfp",     // 39
    "super",        // 40
    "switch",       // 41
    "synchronized", // 42
    "this",         // 43
    "throw",        // 44
    "throws",       // 45
    "transient",    // 46
    "try",          // 47
    "void",         // 48
    "volatile",     // 49
    "while",        // 50
    "goto",         // 51
    "const",        // 52
    "true",         // 53
    "false",        // 54
    "null",         // 55
};

